Repository Five-Rookies/final-project, pull requests merged in 2023-12, with the labels that each got.

#98 refactor: 폴더 구조 리팩터링
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/detail/[id]/_components/DetailHeader.tsx
  src/app/(meetUp)/detail/[id]/_components/RelatedVedio.tsx
  src/app/(meetUp)/detail/[id]/detail.module.scss
  src/app/(meetUp)/detail/[id]/page.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/live.module.scss
  src/app/(meetUp)/live/page.tsx
  src/app/(meetUp)/meetup/_components/MeetupEventButtons.tsx
  src/app/(meetUp)/meetup/_components/MeetupList.tsx
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/(meetUp)/meetup/layout.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/(meetUp)/meetup/page.tsx
  src/components/layout/Header.tsx
Labels: Refactor

#99 refactor: 메인페이지 및 공통 컴포넌트 폴더 구조 수정
  src/app/(main)/@main/_components/ChristmasCounter.tsx
  src/app/(main)/@main/page.tsx
  src/app/(main)/@meetuplist/_components/MainMeetupList.tsx
  src/app/(main)/@meetuplist/page.tsx
  src/app/(main)/@slot/page.tsx
  src/app/(main)/@survey/page.tsx
  src/app/_components/DropDownMenu.tsx
  src/app/_components/Footer.tsx
  src/app/_components/Header.tsx
  src/app/_components/HeaderInput.tsx
  src/app/_components/footer.module.scss
  src/app/_components/header.module.scss
  src/app/layout.tsx
  src/app/page.tsx
  src/components/home/Streaming.tsx
Labels: Refactor

#105 Feat/socket
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/detail.module.scss
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/live.module.scss
  src/app/(meetUp)/live/page.tsx
  src/app/globals.scss
  src/type/SupabaseResponse.ts
  src/utils/apiRequest/commentsApiRequest.ts
Labels: Feat

#106 feat: 메인페이지 meetuplist 더보기 버튼 클릭시 4개씩 나오는 기능 작업중
  public/assets/leaf.png
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/MainMenu.tsx
  src/app/(common)/_components/header.module.scss
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/_components/MainMeetupList.tsx
  src/app/_components/MeetupList.tsx
  src/app/page.module.scss
Labels: Feat

#109 add : supabase 회원가입,로그인,로그아웃 함수 생성
  src/app/(sign)/_components/SignIn.tsx
  src/app/(sign)/_components/SignUp.tsx
  src/utils/apiRequest/signUserSupabase.ts
Labels: Add

#107 refactor: socket 코드 수정 #104
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/live.module.scss
  src/app/(meetUp)/live/page.tsx
  src/type/SupabaseResponse.ts
  src/utils/apiRequest/commentsApiRequest.ts
Labels: Refactor

#112 fix: 댓글 수정 에러 해결
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/utils/apiRequest/commentsApiRequest.ts
Labels: Fix

#114 feat: 로그인/회원가입 기능 구현
  package-lock.json
  package.json
  src/app/(common)/_components/MainMenu.tsx
  src/app/(sign)/_components/SignIn.tsx
  src/app/(sign)/_components/SignUp.tsx
  src/app/(sign)/_components/sign.module.scss
  src/middleware.ts
  src/utils/apiRequest/signUserSupabase.ts
Labels: Feat

#123 fix/socket 채팅 에러 1차 해결
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/page.tsx
  src/app/(sign)/_components/SignUp.tsx
  src/type/SupabaseResponse.ts
Labels: Fix

#130 feat: 방송 시작 확인
  src/app/(meetUp)/live/_components/LiveButton.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/error.tsx
  src/app/(meetUp)/live/live.module.scss
  src/app/(meetUp)/live/page.tsx
  src/app/_components/ChristmasCounter.tsx
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/defaultApiSetting.ts
  src/utils/apiRequest/liveApiRequest.ts
  src/utils/calculateTimeUntilDay.ts
Labels: Refactor, Feat

#132 feat: 모임 삭제하기 구현 #129
  src/app/(meetUp)/live/_components/LiveButton.tsx
  src/app/(meetUp)/live/page.tsx
  src/utils/apiRequest/liveApiRequest.ts
Labels: Feat

#126 feat: 로그인 시 쿠키에 토큰 저장하는 기능 추가
  src/app/(common)/_components/MainMenu.tsx
  src/app/(meetUp)/meetup/page.tsx
  src/app/(sign)/_components/SignIn.tsx
  src/app/(sign)/_components/SignUp.tsx
  src/app/auth/callback/route.ts
  src/app/auth/login/route.ts
  src/app/auth/logout/route.ts
  src/app/auth/sign-up/route.ts
  src/app/not-found.tsx
  src/middleware.ts
  src/utils/apiRequest/signUserSupabase.ts
Labels: Feat

#137 fix: header 등장 애니메이션, 바깥영역 클릭시 닫히도록 수정
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/MainMenu.tsx
  src/app/(common)/_components/header.module.scss
Labels: Fix

#140 feat/refactor: 로그인 관련 함수 utils 분리 및 회원가입 인풋 유효성 검사 기능 추가
  src/app/(common)/_components/MainMenu.tsx
  src/app/(sign)/_components/SignIn.tsx
  src/app/(sign)/_components/SignUp.tsx
  src/utils/apiRequest/signUserSupabase.ts
Labels: Refactor, Feat

#142 fix : supabase 연동 문제 해결 #129
  src/app/(meetUp)/live/_components/LiveButton.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/page.tsx
  src/type/SupabaseResponse.ts
  src/utils/apiRequest/defaultApiSetting.ts
  src/utils/apiRequest/liveApiRequest.ts
  src/utils/apiRequest/signUserSupabase.ts
Labels: Fix

#143 add/style : 모달data에 videoId,thumbnailUrl 추가 및 버튼 스타일 수정
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/_components/_datePicker/DatePicker.tsx
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/_components/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/page.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateMeetUpButton.tsx
  src/app/(meetUp)/detail/[id]/_components/RelatedVedio.tsx
  src/app/(meetUp)/detail/[id]/detail.module.scss
  src/app/(meetUp)/detail/[id]/page.tsx
  src/app/datepicker.scss
  src/status/store.ts
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/meetupApiRequest.ts
Labels: Design, Feat, Add

#146 feat/design: 설문조사 데이터 연동 및 클릭이벤트 구현, 공통 버튼 스타일 추가
  package-lock.json
  package.json
  src/app/_components/Survey.tsx
  src/app/_components/SurveyGraph.tsx
  src/app/globals.scss
  src/app/page.module.scss
  src/utils/apiRequest/defaultApiSetting.ts
  src/utils/apiRequest/surveyApiRequest.ts
Labels: Design, Feat

#148 feat: 재생시간 조절 #147
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/live.module.scss
  src/app/(meetUp)/live/page.tsx
  src/status/store.ts
Labels: Feat

#152 design/refactor: 설문조사 그래프 색상 변경, 더보기 버튼 기능 커스텀훅으로 분리
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/_components/MainMeetupList.tsx
  src/app/_components/SurveyGraph.tsx
  src/app/page.module.scss
  src/hooks/useLoadMore.ts
Labels: Design, Refactor

#154 feat: 참가하기 적용 및 시간함수 및 sort 적용 #150
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/_components/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/meetup/_components/MeetupList.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/globalButton.module.scss
  src/app/globals.scss
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/liveApiRequest.ts
  src/utils/apiRequest/meetupApiRequest.ts
  src/utils/calculateTimeUntilDay.ts
Labels: Feat

#155 feat: 헤더 로그인/로그아웃 시 메뉴 변경되는 기능 추가
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/header.module.scss
  src/app/(sign)/_components/SignIn.tsx
  src/hooks/useYoutubeApiRequest.ts
  src/middleware.ts
  src/status/store.ts
  src/utils/apiRequest/signUserSupabase.ts
Labels: Feat

#158 feat: supabase Database type 추가 #157
  src/type/supabase.ts
Labels: Feat

#159 feat: 모바일해상도 header 메뉴버튼 기능 구현, 모바일 해상도 레이아웃 작업
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/header.module.scss
  src/app/page.module.scss
Labels: Design, Feat

#163 feat : 탭 기능 구현 및 로딩 화면 구현
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/_components/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/_components/_meetupModal/meetupModal.module.scss
  src/app/(meetUp)/detail/[id]/layout.tsx
  src/app/(meetUp)/layout.tsx
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(meetUp)/meetup/_components/MeetupList.tsx
  src/app/(meetUp)/meetup/_components/MeetupTabButtons.tsx
  src/app/(meetUp)/meetup/_components/MeetupTabPage.tsx
  src/app/(meetUp)/meetup/_components/MyMeetupList.tsx
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabButtons.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabPage.tsx
  src/app/(meetUp)/meetup/_components/_tab/TabLoading.tsx
  src/app/(meetUp)/meetup/layout.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/(meetUp)/meetup/meetupList/page.tsx
  src/app/(meetUp)/meetup/myMeetupList/page.tsx
  src/app/(meetUp)/meetup/page.tsx
Labels: Feat

#166 feat: 오늘 생성된 라이브 조회 #165
  package-lock.json
  package.json
  src/app/_components/MainMeetupList.tsx
  src/app/_components/MeetupList.tsx
  src/app/page.module.scss
  src/utils/apiRequest/meetupApiRequest.ts
Labels: Feat

#167 refactor: 검색페이지 데이터 통신 서버 컴포넌트로 변경
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/SearchInput.tsx
  src/app/(common)/_components/header.module.scss
  src/app/(common)/search/_components/NoResult.tsx
  src/app/(common)/search/_components/SearchList.tsx
  src/app/(common)/search/page.tsx
  src/utils/apiRequest/youtubeApiRequest.ts
Labels: Refactor

#172 feat: slot 애니메이션 구현, 메인페이지 애니메이션 효과 적용
  public/assets/fonts/establish Retrosans.otf
  src/app/(common)/_components/MainMenu.tsx
  src/app/(common)/_components/ScrollBtn.module.scss
  src/app/(common)/_components/header.module.scss
  src/app/_components/@createSurveyModal/(..)surveyModal/page.tsx
  src/app/_components/@createSurveyModal/(..)surveyModal/surveyModal/_components/SurveyModal.tsx
  src/app/_components/@createSurveyModal/(..)surveyModal/surveyModal/_components/surveyModal.module.scss
  src/app/_components/@createSurveyModal/detault.tsx
  src/app/_components/Main.tsx
  src/app/_components/Modal.module.scss
  src/app/_components/Slot.tsx
  src/app/_components/SlotContent.tsx
  src/app/_components/SlotModal.tsx
  src/app/_components/Survey.tsx
  src/app/_components/SurveyGraph.tsx
  src/app/_components/SurveyModal.tsx
  src/app/globals.scss
  src/app/layout.tsx
  src/app/page.module.scss
  src/app/thems.scss
  src/utils/apiRequest/surveyApiRequest.ts
Labels: Design, Feat

#174 feat:슬롯 결과 카카오톡 공유 #173
  src/app/_components/SlotModal.tsx
  src/app/layout.tsx
  src/app/page.tsx
Labels: Feat

#175 feat/refactor : 좋아요 기능 구현 및 comment 컴포넌트 리팩토링
  public/assets/likeOff.svg
  public/assets/likeOn.svg
  src/app/(meetUp)/@createMeetupModal/default.tsx
  src/app/(meetUp)/_components/_meetupModal/_datePicker/DatePicker.tsx
  src/app/(meetUp)/_components/_meetupModal/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/detail/[id]/detail.module.scss
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabButtons.tsx
  src/type/Component.ts
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/likeApiRequest.ts
  src/utils/relativeDate.ts
Labels: Refactor, Feat

#181 fix : 댓글 프로필 이미지 랜덤 삭제
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/RelatedVedio.tsx
  src/app/_components/SlotModal.tsx
Labels: Fix

#176 feat/refactor : youtube api 통신 서버 컴포넌트로 변경 및 무한스크롤 구현
  src/app/(common)/_components/Footer.tsx
  src/app/(common)/search/_components/SearchList.tsx
  src/app/(common)/search/page.tsx
  src/app/(meetUp)/detail/[id]/_components/RelatedVedio.tsx
  src/app/(meetUp)/detail/[id]/error.tsx
  src/app/(meetUp)/detail/[id]/page.tsx
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabPage.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/(meetUp)/meetup/page.tsx
  src/app/_components/Survey.tsx
  src/app/_components/SurveyModal.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useLoadMore.ts
  src/hooks/useScrollBottom.ts
  src/utils/apiRequest/youtubeApiRequest.ts
  src/utils/youtubRequest/videoInfoCookieClient.ts
  src/utils/youtubRequest/videoInfoCookieServer.ts
  src/utils/youtubRequest/youtubeApiRequest.ts
  src/utils/youtubRequest/youtubeJsonRequest.ts
  src/utils/youtubRequest/youtubeRequest.ts
Labels: Refactor, Feat

#182 refactor: 비디오 상세 페이지 쿠키 사용하여 정보 표시하는 것으로 수정
  public/videos/popular.json
  public/videos/searchByChannels/search-by-channel-id-UC1x03ziDHPct2xTikLyfMDA.json
  public/videos/searchByChannels/search-by-channel-id-UC37fRkl_iIjDAr9pf0FFzGA.json
  public/videos/searchByChannels/search-by-channel-id-UC4ZA57iJrf73bJlApKFeLRw.json
  public/videos/searchByChannels/search-by-channel-id-UC98Dpw8CHzoPuEYbL9SnXWQ.json
  public/videos/searchByChannels/search-by-channel-id-UCAyvCxdhYV-Zg7PSGZJoQ2A.json
  public/videos/searchByChannels/search-by-channel-id-UCDNvRZRgvkBTUkQzFoT_8rA.json
  public/videos/searchByChannels/search-by-channel-id-UCI2T1_bAtgnKKzfhw3Qib9w.json
  public/videos/searchByChannels/search-by-channel-id-UCK5fO9Q2gitao0M5yQvPnvw.json
  public/videos/searchByChannels/search-by-channel-id-UCLItMtuFPIZ-Q0m_oOVwB2Q.json
  public/videos/searchByChannels/search-by-channel-id-UCQ2O-iftmnlfrBuNsUUTofQ.json
  public/videos/searchByChannels/search-by-channel-id-UCSknObj2PGGK6KCkTyc5Kkw.json
  public/videos/searchByChannels/search-by-channel-id-UCTQVIXvcHrR9jYoJ6qaBAow.json
  public/videos/searchByChannels/search-by-channel-id-UCUQVGXF4U-PupGCPdIRX4Qw.json
  public/videos/searchByChannels/search-by-channel-id-UCUyfkq9e9ZfPzxOW5WQ9rzQ.json
  public/videos/searchByChannels/search-by-channel-id-UCWYzc_p0GgfCepIWDHGFmEg.json
  public/videos/searchByChannels/search-by-channel-id-UCXEKwWflysXu312NmIP_dlw.json
  public/videos/searchByChannels/search-by-channel-id-UCbD8EppRX3ZwJSou-TVo90A.json
  public/videos/searchByChannels/search-by-channel-id-UCepUWUpH45hRTi-QePdq1Bg.json
  public/videos/searchByChannels/search-by-channel-id-UCmJEpV4hLzGWLU5rrdOHMhQ.json
  public/videos/searchByChannels/search-by-channel-id-UCnBht7BrOx-A328KFXgysqQ.json
  public/videos/searchByChannels/search-by-channel-id-UCnCEKlzi52Yzj2JdBFhKVEA.json
  public/videos/searchByChannels/search-by-channel-id-UCtCiO5t2voB14CmZKTkIzPQ.json
  public/videos/searchByChannels/search-by-channel-id-UCw-kXdzxMdMdLNI0ZlFFbmA.json
  public/videos/searchByChannels/search-by-channel-id-UCx6jsZ02B4K3SECUrkgPyzg.json
  public/videos/videoCategories.json
  src/app/(common)/_components/SearchInput.tsx
  src/app/(common)/search/_components/SearchList.tsx
  src/app/(common)/search/page.tsx
  src/app/(meetUp)/detail/[id]/page.tsx
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/_components/MainMeetupList.tsx
  src/hooks/useInfiniteScroll.ts
  src/hooks/useYoutubeApiRequest.ts
  src/utils/cookieClient.ts
  src/utils/cookieServer.ts
  src/utils/youtubRequest/videoInfoCookieClient.ts
Labels: Refactor

#185 fix & refactor : 탭버튼 로컬 저장 로직 버그 수정 및 반응형 디자인 수정
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabButtons.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabPage.tsx
  src/app/(meetUp)/meetup/layout.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/globalButton.module.scss
  src/app/globals.scss
Labels: Fix, Refactor

#187 feat: meetup 좋아요 기능 추가
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/_components/RelatedVedio.tsx
  src/app/(meetUp)/detail/[id]/page.tsx
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/auth/sign-up/route.ts
  src/type/Component.ts
  src/utils/apiRequest/likeApiRequest.ts
Labels: Feat

#189 refactor/add : 모임 생성 모달에 데이터 추가 및 유효성 검사 추가
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/page.tsx
  src/app/(meetUp)/_components/_meetupModal/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateMeetUpButton.tsx
  src/app/(meetUp)/detail/[id]/meetupModal/page.tsx
  src/app/(meetUp)/detail/[id]/page.tsx
  src/status/store.ts
  src/type/Component.ts
Labels: Refactor, Add

#191 feat: 유저 정보 public으로 관리하는 기능 추가
  src/app/(common)/_components/Profile.tsx
  src/app/(common)/_components/header.module.scss
  src/app/(sign)/_components/FindPassword.tsx
  src/app/(sign)/_components/SignIn.tsx
  src/app/(sign)/_components/SignInput.tsx
  src/app/(sign)/_components/SignUp.tsx
  src/app/(sign)/_components/sign.module.scss
  src/app/(sign)/resetpassword/page.tsx
  src/app/(sign)/signIn/findPassword/page.tsx
  src/app/(sign)/signIn/page.tsx
  src/app/(sign)/signUp/page.tsx
  src/app/auth/callback/route.ts
  src/app/auth/login/route.ts
  src/app/auth/logout/route.ts
  src/app/auth/sign-up/route.ts
  src/middleware.ts
  src/utils/apiRequest/profileApiRequest.ts
  src/utils/apiRequest/signUserSupabase.ts
Labels: Feat

#194 refactor : meetup 페이지 반응형 최종 로딩컴포넌트 리팩토링
  src/app/(meetUp)/meetup/_components/MeetupList.tsx
  src/app/(meetUp)/meetup/_components/MyMeetupList.tsx
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabPage.tsx
  src/app/(meetUp)/meetup/layout.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
Labels: Refactor

#195 refactor/fix: 메인 반응형 수정 및 에러창 뜨는 부분 수정
  src/app/(common)/_components/header.module.scss
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/_components/Main.tsx
  src/app/_components/Modal.module.scss
  src/app/_components/Slot.tsx
  src/app/_components/SlotContent.tsx
  src/app/_components/Survey.tsx
  src/app/_components/SurveyGraph.tsx
  src/app/_components/SurveyModal.tsx
  src/app/page.module.scss
  src/type/SupabaseResponse.ts
  src/utils/apiRequest/surveyApiRequest.ts
Labels: Fix, Refactor

#197 fix: survey 구조 변경
  src/app/_components/Survey.tsx
  src/app/_components/SurveyModal.tsx
Labels: Fix

#199 feat : 댓글 수정 삭제 본인 것만 할 수 있도록 구현 및 비밀 번호 찾기 완료 하면 홈으로 리다이렉트 구현
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(sign)/resetpassword/page.tsx
Labels: Feat

#201 fix: 크리스마스 d-day 수정 #200
  src/app/_components/ChristmasCounter.tsx
  src/app/_components/Main.tsx
  src/app/page.module.scss
  src/utils/calculateTimeUntilDay.ts
Labels: Fix

#208 feat/refactor: 프로필 모달 기능 추가 및 리팩터링
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/Profile.tsx
  src/app/(common)/_components/header.module.scss
  src/app/thems.scss
  src/utils/apiRequest/profileApiRequest.ts
Labels: Refactor, Feat

#212 fix: 헤더 로고 및 프로필 모달 위치 수정
  public/assets/header_logo.svg
  public/assets/header_logo_white.svg
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/MainMenu.tsx
  src/app/(common)/_components/Profile.tsx
  src/app/(common)/_components/header.module.scss
  src/app/thems.scss
Labels: Fix

#211 fix : user 조회 테이블 profile 테이블로 변경
  src/app/(common)/_components/Profile.tsx
  src/app/(meetUp)/_components/_meetupModal/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/live/_components/LiveButton.tsx
  src/app/(meetUp)/live/live.module.scss
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(meetUp)/meetup/_components/MeetupList.tsx
  src/app/(meetUp)/meetup/_components/MyMeetupList.tsx
  src/app/(meetUp)/meetup/layout.tsx
  src/app/_components/SlotModal.tsx
  src/app/page.module.scss
  src/type/Component.ts
  src/type/supabase.ts
  src/utils/apiRequest/profileApiRequest.ts
Labels: Fix, Refactor

#206 fix/refactor: 설문 제출시 모달 닫히도록 수정, 설문조사 그래프 코드 리팩토링
  src/app/_components/Survey.tsx
  src/app/_components/SurveyGraph.tsx
  src/app/_components/SurveyModal.tsx
Labels: Fix, Refactor

#214 feat : 서버에 요청 하는 로직 디바운스 처리
  package-lock.json
  package.json
  src/app/(common)/_components/Header.tsx
  src/app/(meetUp)/_components/_meetupModal/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(sign)/resetpassword/page.tsx
  src/app/(sign)/signIn/findPassword/page.tsx
  src/app/(sign)/signIn/page.tsx
  src/app/(sign)/signUp/page.tsx
  src/app/_components/SlotContent.tsx
  src/app/_components/SurveyModal.tsx
  src/utils/apiRequest/signUserSupabase.ts
Labels: Feat

#217 fix: 메인 모달창 다크모드, 슬롯 z-index, 설문조사 반응형 레이아웃 수정
  src/app/_components/Modal.module.scss
  src/app/_components/Survey.tsx
  src/app/page.module.scss
Labels: Fix

#218 refactor: 전체적인 타입 수정 및 불필요한 import, 주석 정리
  src/app/(common)/_components/Header.tsx
  src/app/(common)/_components/MainMenu.tsx
  src/app/(common)/_components/Profile.tsx
  src/app/(common)/developers/page.tsx
  src/app/(meetUp)/@createMeetupModal/(.)detail/[id]/meetupModal/page.tsx
  src/app/(meetUp)/@createMeetupModal/default.tsx
  src/app/(meetUp)/_components/_meetupModal/_meetupModal/MeetupModal.tsx
  src/app/(meetUp)/detail/[id]/_components/Comment.tsx
  src/app/(meetUp)/detail/[id]/_components/CommentList.tsx
  src/app/(meetUp)/detail/[id]/_components/CreateComment.tsx
  src/app/(meetUp)/detail/[id]/meetupModal/page.tsx
  src/app/(meetUp)/live/_components/LiveButton.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
  src/app/(meetUp)/live/_components/LiveStream.tsx
  src/app/(meetUp)/live/page.tsx
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(meetUp)/meetup/_components/MeetupList.tsx
  src/app/(meetUp)/meetup/_components/MyMeetupList.tsx
  src/app/(meetUp)/meetup/_components/VideoList.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabButtons.tsx
  src/app/(meetUp)/meetup/layout.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/(meetUp)/meetup/meetupList/page.tsx
  src/app/(meetUp)/meetup/myMeetupList/page.tsx
  src/app/(sign)/resetpassword/page.tsx
  src/app/(sign)/signIn/findPassword/page.tsx
  src/app/_components/@createSurveyModal/detault.tsx
  src/app/_components/Main.tsx
  src/app/_components/MainMeetupList.tsx
  src/app/_components/Modal.module.scss
  src/app/_components/Slot.tsx
  src/app/_components/SlotContent.tsx
  src/app/_components/SlotModal.tsx
  src/app/_components/Survey.tsx
  src/app/_components/SurveyGraph.tsx
  src/app/_components/SurveyModal.tsx
  src/app/auth/callback/route.ts
  src/app/auth/login/route.ts
  src/app/auth/logout/route.ts
  src/app/auth/sign-up/route.ts
  src/app/page.module.scss
  src/type/Component.ts
  src/type/SupabaseResponse.ts
  src/type/supabase.ts
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/profileApiRequest.ts
  src/utils/apiRequest/signUserSupabase.ts
  src/utils/apiRequest/surveyApiRequest.ts
Labels: Refactor, Chore

#219 design/refactor : meetup 페이지 반응형 및 코드 수정
  src/app/(meetUp)/meetup/_components/MeetupBox.tsx
  src/app/(meetUp)/meetup/_components/_tab/MeetupTabButtons.tsx
  src/app/(meetUp)/meetup/meetup.module.scss
  src/app/globalButton.module.scss
Labels: Design, Refactor

#205 add: youtube 영상 json 데이터 추가 수집
  public/videos/christmas/christmasPopular_v1.json
  public/videos/christmas/searchByChannels/search-by-channel-id- UCoxT1kQSLq564FwpK473w-g.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC-8xPSlb0xDYqSuIWcdcPAQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC-9Tn-iH6W_187YwCOf7CGw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC0dJz7rZ_OuV6nNG14dDAmg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC1B6SalAoiJD7eHfMUA9QrA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC1tqsiHUcbbDgGSbyLF7Z5Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC3mG7uBpHaBUiTPzx4IOgcQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC4p55vEp6hc1fZ-raIGQw9Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC5OStgYPn8_UbILMFNFF_-w.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC78PMQprrZTbU0IlMDsYZPw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC9ta639M37zzWKwo7kKc80A.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCA-x_p2coOIWWdDf80DQ8sA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCBnMxlW70f0SB4ZTJx124lw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCCuVtrXizlmVfADF4eBIvUA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCDdtq91zPKK6urACRvsX4Mg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCDkrk2wAitM9jFB523Q37Qw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCGMz6JDxy0jlh-Rszf0tzUg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCGsJRpGI3iFpf0lIUIgbsBw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCI8vZWRSzUmJAMveJTxOo9g.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCKBt6VowYGmBpXFf3rVhaQA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCKHV4MGtdlMb3aCGotUjzsQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCKxknVfRWj3YKZuE_qiWZ4Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCL4Ox6SLnHCrSILVsgrQSpg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCPUeGC_AL-OnDQORKhRm6iA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCQ208ny4iVFEoHOTvNKnx3g.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCSGC87iX0QhnIfUOI_B_Rdg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCURnLWTrLZVv_KiVaeZakog.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCUkaBPcyqVjhSdLWppNL8SQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCUxfAC7VlejlRtJhWdTG3qQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCV-rnbAzn5zsEWG6ZI3Jw1Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCVut4hqvrjQC4qDE3oc5qig.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCY4x5L6JrCJfaROUkuJEivA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCYMEXdU9oVJ6JUoyL8Fv06Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCaS8JH5U5nMaOfrSVYnbOTQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCbsHYIZwk9pZIMp53ciDjOw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCdp8WGk7l78AIGooOvO35IQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCijBTYEiKT1OJO54C6PnRqw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCjIfXBwSHmCzbdb5fDvUEEg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCk1rgRaCucSef10-fuzD2TA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCliRjcwaUW-ozT9TeYTfoug.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCmjNKt6kITwaZTqvWuaSPLg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCnDahTFzq0NNIttHVKLBUUw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCnabt_BunUVVk1PcSd8CO9Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCoBcjaSab_CLwBOKe-8Fvjw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCq3RYCIkwYmIDbtI0ThEk6A.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCqEAlQNINdzjSpvCgplQrvA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCqXwKu6dKobXEQFhdKtiJLQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCu4X3ZAoq6nToNJNNoQuICA.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCuI7J9khfdYqzDN8nDriDxg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCusW_eHZw_tWLVRv0fzxj_g.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCvNGDjkxo4H0DfbyL_djc6Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCweFCeE7R38-pvPl6RifWpw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCxGyH7vzYkZwFseTUa3yZpQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCx_dzPI6efSohgtOkAG43-A.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCyzGps9pBVA1x0tgffSkoew.json
Labels: Add

#221 fix: 검색어 재입력시 조회 안되는 오류 수정
  src/app/(common)/search/_components/SearchList.tsx
  src/app/(common)/search/page.tsx
Labels: Fix

#222 fix: 채팅에러 및 메뉴 수정
  src/app/(common)/_components/MainMenu.tsx
  src/app/(meetUp)/live/_components/LiveChat.tsx
Labels: Fix

#220 fix: 모바일 반응형 헤더 짤림 현상 수정
  src/app/(common)/_components/header.module.scss
Labels: Fix
