Repository Five-Rookies/final-project, pull requests merged in 2023-11, with the labels that each got.

#4 Feat: 검색기능 #3
  src/app/layout.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
Labels: Fix, Feat

#7 Feat: 메인페이지 조회 기능 구현 #5
  package-lock.json
  package.json
  src/app/mainList/page.module.scss
  src/app/mainList/page.tsx
  src/utils/relativeDate.ts
  tsconfig.json
Labels: Feat

#12 Feat: 상세페이지 마크업 및 데이터 불러오기 기능 구현
  public/assets/left-arrow.png
  src/app/detail/[id]/detail.module.scss
  src/app/detail/[id]/layout.tsx
  src/app/detail/[id]/page.tsx
  src/app/globals.css
  src/app/mainList/page.tsx
  src/type/Api.ts
Labels: Feat

#15 Refactor: 상세페이지 컴포넌트 분리 및 페이지 이동 시 쿼리 정보 변경
  src/app/detail/[id]/detail.module.scss
  src/app/detail/[id]/page.tsx
  src/app/mainList/page.tsx
  src/components/detail/RelatedVedio.module.scss
  src/components/detail/RelatedVedio.tsx
  src/type/Api.ts
Labels: Refactor

#18 Refactor : mainList 데이터 요청 응답 코드 리팩토링 및 server , client 컴포넌트 분리 #16
  src/app/mainList/page.tsx
  src/components/mainList/VideoList.tsx
Labels: Refactor

#21 design: header 반응형 및 메인 #20
  package-lock.json
  package.json
  public/assets/header_close_icon.svg
  public/assets/header_logo.svg
  public/assets/header_search_icon.svg
  public/assets/santa.png
  public/assets/tree.png
  src/app/globals.css
  src/app/mainList/page.module.scss
  src/app/page.module.css
  src/app/page.module.scss
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/Header.tsx
  src/components/Search.tsx
  src/components/header.module.scss
Labels: Design

#28 Refactor: 상세페이지 데이터 통신 api로 변경
  src/app/detail/[id]/layout.tsx
  src/app/detail/[id]/page.tsx
  src/components/Header.tsx
  src/components/Search.tsx
  src/components/detail/RelatedVedio.tsx
  src/components/mainList/VideoList.tsx
Labels: Refactor

#34 feat: supabase api util 함수 생성
  src/utils/apiRequest/commentsApiRequest.ts
Labels: Feat

#35 feat: api 데이터 통신 기능 utils 함수 분리 및 적용
  src/app/detail/[id]/RelatedVedio.tsx
  src/app/detail/[id]/page.tsx
  src/app/mainList/page.tsx
  src/app/search/page.tsx
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/youtubeApiRequest.ts
Labels: Refactor, Feat

#39 feat, refactor: 상세페이지 댓글 추가로 레이아웃 수정 및 api utils 함수 변경
  public/assets/left-arrow.png
  public/assets/left-arrow.svg
  src/app/detail/[id]/Comments.tsx
  src/app/detail/[id]/DetailHeader.tsx
  src/app/detail/[id]/RelatedVedio.tsx
  src/app/detail/[id]/detail.module.scss
  src/app/detail/[id]/layout.tsx
  src/app/detail/[id]/page.tsx
  src/app/mainList/page.tsx
  src/app/search/page.tsx
  src/utils/apiRequest/commentsApiRequest.ts
Labels: Refactor, Feat

#40 feat, fix : 다크모드 구현 및 다크모드 실행 중 hidration 에러 해결
  package-lock.json
  package.json
  src/app/detail/[id]/RelatedVedio.tsx
  src/app/detail/[id]/detail.module.scss
  src/app/detail/[id]/page.tsx
  src/app/globals.scss
  src/app/mainList/page.module.scss
  src/app/mainList/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/thems.scss
  src/components/layout/Header.tsx
  src/components/layout/HeaderInput.tsx
  src/components/layout/header.module.scss
  src/status/store.ts
  src/type/SupabaseRespons.ts
Labels: Fix, Feat

#46 feat: 댓글 컴포넌트 수정/삭제 기능 추가
  src/app/detail/[id]/Comment.tsx
  src/app/detail/[id]/CommentList.tsx
  src/app/detail/[id]/detail.module.scss
  src/app/detail/[id]/page.tsx
  src/type/SupabaseRespons.ts
  src/utils/apiRequest/commentsApiRequest.ts
Labels: Feat

#50 refactor: 댓글 에러 수정
  src/app/detail/[id]/Comment.tsx
  src/app/detail/[id]/CommentList.tsx
  src/app/detail/[id]/detail.module.scss
  src/app/page.module.scss
Labels: Refactor

#52 refactor: 스크롤버튼 컴포넌트 분리, 스크롤 버튼 기능 수정
  .env
  src/app/detail/[id]/RelatedVedio.tsx
  src/app/detail/[id]/page.tsx
  src/app/mainList/VideoList.tsx
  src/app/mainList/page.module.scss
  src/app/thems.scss
  src/components/ScrollBtn.module.scss
  src/components/ScrollBtn.tsx
Labels: Refactor

#55 fix: 스크롤 버튼이 없는 상태에서 스크롤시 버튼 나타나도록 수정
  src/components/ScrollBtn.module.scss
  src/components/ScrollBtn.tsx
Labels: Fix

#56 refactor: json 데이터 크리스마스 컨셉으로 수정
  public/videos/christmas/christmasPopular_v1.json
  public/videos/christmas/christmasPopular_v2.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC-9Tn-iH6W_187YwCOf7CGw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC0dJz7rZ_OuV6nNG14dDAmg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC1tqsiHUcbbDgGSbyLF7Z5Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC4p55vEp6hc1fZ-raIGQw9Q.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UC5OStgYPn8_UbILMFNFF_-w.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCDdtq91zPKK6urACRvsX4Mg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCGMz6JDxy0jlh-Rszf0tzUg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCGsJRpGI3iFpf0lIUIgbsBw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCKHV4MGtdlMb3aCGotUjzsQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCQ208ny4iVFEoHOTvNKnx3g.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCSGC87iX0QhnIfUOI_B_Rdg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCURnLWTrLZVv_KiVaeZakog.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCUkaBPcyqVjhSdLWppNL8SQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCVut4hqvrjQC4qDE3oc5qig.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCaS8JH5U5nMaOfrSVYnbOTQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCbsHYIZwk9pZIMp53ciDjOw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCdp8WGk7l78AIGooOvO35IQ.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCijBTYEiKT1OJO54C6PnRqw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCjIfXBwSHmCzbdb5fDvUEEg.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCnDahTFzq0NNIttHVKLBUUw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCq3RYCIkwYmIDbtI0ThEk6A.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCweFCeE7R38-pvPl6RifWpw.json
  public/videos/christmas/searchByChannels/search-by-channel-id-UCxGyH7vzYkZwFseTUa3yZpQ.json
  public/videos/christmas/videoCategories.json
  src/app/detail/[id]/RelatedVedio.tsx
  src/app/detail/[id]/page.tsx
  src/app/mainList/page.module.scss
  src/app/mainList/page.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/home/VideoList.tsx
  src/type/Api.ts
  src/utils/apiRequest/youtubeApiRequest.ts
Labels: Refactor

#59 Fix&feat : header 다크모드 수정 및 에러페이지 생성
  public/assets/header_logo.svg
  public/assets/header_logo_symbol.svg
  public/assets/header_logo_white.svg
  public/assets/header_moon.svg
  public/assets/header_sun.svg
  public/assets/not-found.png
  public/assets/snowman.png
  src/app/detail/[id]/CommentList.tsx
  src/app/detail/[id]/CreateComment.tsx
  src/app/detail/[id]/detail.module.scss
  src/app/globals.scss
  src/app/not-found.tsx
  src/app/page.module.scss
  src/app/page.tsx
  src/app/thems.scss
  src/components/layout/Header.tsx
  src/components/layout/HeaderInput.tsx
  src/components/layout/header.module.scss
Labels: Fix, Feat

#61 design: 요소 위치 수정
  src/app/page.module.scss
  src/app/page.tsx
Labels: Design

#75 fix: youtube api 요청 에러 관리
  src/app/detail/[id]/RelatedVedio.tsx
  src/app/detail/[id]/detail.module.scss
  src/app/detail/[id]/page.tsx
  src/app/page.tsx
  src/app/search/page.tsx
  src/components/home/VideoList.tsx
  src/hooks/useExample.tsx
  src/hooks/useYoutubeApiRequest.ts
  src/status/store.ts
  src/utils/apiRequest/youtubeApiRequest.ts
Labels: Fix, Refactor, Feat

#80 feat: 검색결과 없을 경우 안내 페이지 추가
  public/assets/no-results.png
  src/app/loading.tsx
  src/app/search/NoResult.tsx
  src/app/search/page.tsx
  src/app/search/search.module.scss
Labels: Feat

#84 Feat/api
  src/utils/apiRequest/commentsApiRequest.ts
  src/utils/apiRequest/youtubeApiRequest.ts
Labels: Refactor, Feat
